import type { Metadata } from "next";
import { PT_Sans_Narrow } from "next/font/google";
import "./globals.css";
import { AppFooter, AppNavbar } from "@/layouts";

const narrow = PT_Sans_Narrow({
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "UFC - Ultimate Fighting Championship",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={narrow.className}>
        <AppNavbar />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
